### ISSUE TITLE
Variables, Data Types, Constants, Type Casting

### ISSUE THREAD

**Issue by quickwritereader** [BranchAndLink/GoLangFastPaced#1]
Variables, Data Types, Constants, and Type Casting

- [x] #18
- [x] #20 
- [x] #204
- [x] #223

**Comment by gigabright** [comment]
Hazırdı. Branchda.

**Comment by gigabright** [comment]
Bağla getsin )

**Comment by quickwritereader** [comment]
Pr ach da bes. qoy achim yerine

**Comment by quickwritereader** [comment]
@gigabright ehsente.   
 notebook-da yazanda run-da et output-lar chixsin. Bir de ad qoyanda Bele qoy
VariablesTypesAndFalan -> hazirda bash script yazmisham bunlari bunlari markdown-a chevirir hugo sayta elave edende tag-leri boyuk herflere gore ayirir.  Amma heleki automatlashdirilmayib.  
Eyni Adli topikleri bilmirem merge edek yoxsa yanashi qoyaq
