### ISSUE TITLE
BasicIO#mohsun

### ISSUE THREAD

**Issue by quickwritereader** [BranchAndLink/GoLangFastPaced#23]

**Comment by quickwritereader** [comment]
@Mohsun88 branchleri pozdum.
 daha her defe yeni movzu ishleyende main-den branch-yaradacaqsiniz. 
her movzuya uygun branch yaradib ishlemek olar  
movzu bitenden sonra hemin branch merge olub deelte olacaq  
bele etmekle main-le sinxronlughu artiracayiq

**Comment by Mohsun88** [comment]
Oldu @quickwritereader,  baxacam gorum ede bilmesem sene deyecem.

**Comment by quickwritereader** [comment]
@Mohsun88 branch-ler hemishe delete olacaq. 2-3 branch etdikde 
muellif_hedef kimi ad sechin   
meselen
mohsun_arrays
